# Generated by Django 3.2.6 on 2021-08-28 07:02

from django.db import migrations, models
import retro_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrouser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=retro_api.models.user_profile_picture),
        ),
    ]
